version: '3.8'

services:
  pokenea-app:
    image: julimejia2/pokenea-express:latest
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - NODE_ENV=production
    ports:
      - "4005:4005"
    networks:
      - pokenea-net

networks:
  pokenea-net:
    external: true
